// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1MYOXCimfc5pa88W1zb4c-g1AHFYo4iY',
    appId: '1:653064783691:web:aa684cd75ff24b5bd94ace',
    messagingSenderId: '653064783691',
    projectId: 'kto-na-bibe',
    authDomain: 'kto-na-bibe.firebaseapp.com',
    storageBucket: 'kto-na-bibe.firebasestorage.app',
    measurementId: 'G-M8B5EP601P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPacZWjmyhsHhO5GBV7V7o7kdZhg7LLEU',
    appId: '1:653064783691:android:ed64c61b10093ebdd94ace',
    messagingSenderId: '653064783691',
    projectId: 'kto-na-bibe',
    storageBucket: 'kto-na-bibe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIsDyQ60o90moXXvtMsJO0aCTRy3QBwM',
    appId: '1:653064783691:ios:4475c26d75cd48bdd94ace',
    messagingSenderId: '653064783691',
    projectId: 'kto-na-bibe',
    storageBucket: 'kto-na-bibe.firebasestorage.app',
    iosClientId: '653064783691-tr0qbounnq8rbhjko7qv21o9jpkimcii.apps.googleusercontent.com',
    iosBundleId: 'com.example.ktoNaBibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1MYOXCimfc5pa88W1zb4c-g1AHFYo4iY',
    appId: '1:653064783691:web:76923902115fc3f1d94ace',
    messagingSenderId: '653064783691',
    projectId: 'kto-na-bibe',
    authDomain: 'kto-na-bibe.firebaseapp.com',
    storageBucket: 'kto-na-bibe.firebasestorage.app',
    measurementId: 'G-TGDNQK6S6H',
  );
}
